### PR TITLE
DMStationMicro first version

### PR DESCRIPTION
**Pull request by sp2ong**
DMRStationMicro glade first version

### CODE REVIEW

**Comment by sp2ong** [comment]
I created the first version of DMRStationMicro.glade based on DMRStationMini.glade and changed the size of all elements using scale factors for the X dimension 0.66 and the Y dimension 0.75.
I used GLADE under Linux Ubuntu for GTK 3.

**Comment by ea3ihi** [comment]
Thanks for the PR, the idea is that you should be able to compile and test your changes before submitting a pull request.

Please update the application from the DMRStation-release repository and test the option miniUI=2 to see how it works. In my tests in a 800x480 screen i have the impression that the UI was bigger than 320x240.

**Comment by sp2ong** [comment]
OK, But I currently not find a way how to compile DMRStation on Orange Pi Zero. I don't have and use eclipse.
I will try to find the option to compile directly on Orange PI Zero with a gcc compiler and then I will be able to better adjust the size parameters for 240x320 TFT

**Comment by ea3ihi** [comment]
I have added a makefile that worked for me in a raspi 3b. I had to install the packages libgtk-3-dev and  libpulse-dev in order to build the application. Please give it a go

**Comment by sp2ong** [comment]
OK thank you

**Comment by sp2ong** [comment]
Hi,

I compiled on my Orange Pi Zero and please remove my pull request DMRStationMicro.glad and I will come back when I verify 240x320 on my LCD TFT display and send the pull request again

Thanks for makefile :-)

**Comment by ea3ihi** [comment]
Nice that you can compile, i close this PR

**Comment by sp2ong** [comment]
Only one warning was:

gcc -Wall -g -o `pkg-config --cflags gtk+-3.0 libcrypto`   -c -o src/ptt.o src/ptt.c
src/ptt.c: In function ‘ptt_init’:
src/ptt.c:25:7: warning: implicit declaration of function ‘open’; did you mean ‘popen’? [-Wimplicit-function-declaration]
  fd = open(chrdev_name, 0);
       ^~~~
       popen

the others were without any warning :-)

**Pull request closed without merging**
